/* LIBRARY FOR POWER SAVINGS */
#include "LowPower.h"

void setup() 
{
  
}

void loop() 
{
  
}

/* PUT THE ARDUINO TO SLEEP FOR 8 SECONDS */
void PowerSavingsMode()
{
  LowPower.powerDown(SLEEP_8S, ADC_OFF, BOD_OFF);
}

// 60 SECONDS = 1 MINUTE
// 3 600 SECONDS = 60 MINUTES
// 3 600 SECONDS (DIVIDED BY) 8 SECONDS = 450 TIMES

// THE POWER SAVING FUNCTION WILL HAVE TO BE EXECUTED 450 TIMES PER HOUR.
// SO IF WE WANT THE ARDUINO TO SLEEP FOR 12 HOURS (SO THAT IT EXECUTES THE WATERING PROCEDURES ONCE EVERY 12 HOURS) WE HAVE TO EXECUTE THE POWER SAVING FUNCTION 450 * 12 = 5 400 TIMES.

// 43 200 SECONDS = 12 HOURS | 43 200 / 8 = 5 400 TIMES.
// 
